export const GET_MUSIC = "GET_MUSIC"
export const GET_MUSIC_SINGLE = "GET_MUSIC_SINGLE"
export const LOADING = "LOADING"
export const USER_LOGIN = "USER_LOGIN"
export const LOAD_USER = "LOAD_USER"
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED"